GET http://localhost:3300/users
###
POST http://localhost:3300/users/login
Content-Type: application/json

{
    "email": "email@web.com",
    "password": "password1"
}
###
GET http://localhost:3300/users/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkYjYzNDMwZjY1YjAxNTU3OGY5Yzc5MiIsImlhdCI6MTU3MzcxMjU3MX0.DR7ErjBqynqimJn9QwS2bFJA9es5FLU1mbJ-ehL2TqQ

{
    "email": "email@web.com",
    "password": "password1"
}
###
PATCH http://localhost:3300/users/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkYjYzNDMwZjY1YjAxNTU3OGY5Yzc5MiIsImlhdCI6MTU3MzcxMjU3MX0.DR7ErjBqynqimJn9QwS2bFJA9es5FLU1mbJ-ehL2TqQ

{
    "name": "Your Updated Boi"
}
