GET http://localhost:4000/users

###
POST http://localhost:4000/users
Content-Type: application/json

{
    "name": "Not Unique Email",
    "email": "email@web.com",
    "password": "password3"
}

###
GET http://localhost:4000/users/5db63430f65b015578f9c792

###
PATCH http://localhost:4000/users/5db63430f65b015578f9c792
Content-Type: application/json

{
    "name": "Your Boi"
}
